language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  
  - cargo build --verbose
  - cd fuzz && cargo build --verbose
  - cargo test
notifications:
  email:
    on_success: never
branches:
  only:
    - master
