language: rust
rust:
  - nightly
sudo: false
script:
  - cargo build --verbose
  - cargo test
  - cargo test --example tic-tac-toe
  - cargo test --example oko
notifications:
  email:
    on_success: never
branches:
  only:
    - master
